// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
// Members
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const MEMBER_PROFILE_SUCCESS = 'MEMBER_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Orders
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const ORDER_PROFILE_SUCCESS = 'ORDER_PROFILE_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

//
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';

//
export const TIME_REQUEST_STARTED = 'TIME_REQUEST_STARTED';
export const TIME_REQUEST_FINISHED = 'TIME_REQUEST_FINISHED';
export const TIME_REQUEST_ERROR = 'TIME_REQUEST_ERROR';
